// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	"c2nbe/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/encode/sign_participation",
				Handler: SignParticipationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/encode/sign_registration",
				Handler: SignRegistrationHandler(serverCtx),
			},
		},
	)
}
