// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.31.1
// source: c2n/v1/c2n.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationC2NSignRegistration = "/c2n.v1.C2N/SignRegistration"

type C2NHTTPServer interface {
	// SignRegistration Sends a greeting
	SignRegistration(context.Context, *SignRegisterRequest) (*SignRegisterReply, error)
}

func RegisterC2NHTTPServer(s *http.Server, srv C2NHTTPServer) {
	r := s.Route("/")
	r.POST("/encode/sign_registration", _C2N_SignRegistration0_HTTP_Handler(srv))
}

func _C2N_SignRegistration0_HTTP_Handler(srv C2NHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SignRegisterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationC2NSignRegistration)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SignRegistration(ctx, req.(*SignRegisterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SignRegisterReply)
		return ctx.Result(200, reply)
	}
}

type C2NHTTPClient interface {
	// SignRegistration Sends a greeting
	SignRegistration(ctx context.Context, req *SignRegisterRequest, opts ...http.CallOption) (rsp *SignRegisterReply, err error)
}

type C2NHTTPClientImpl struct {
	cc *http.Client
}

func NewC2NHTTPClient(client *http.Client) C2NHTTPClient {
	return &C2NHTTPClientImpl{client}
}

// SignRegistration Sends a greeting
func (c *C2NHTTPClientImpl) SignRegistration(ctx context.Context, in *SignRegisterRequest, opts ...http.CallOption) (*SignRegisterReply, error) {
	var out SignRegisterReply
	pattern := "/encode/sign_registration"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationC2NSignRegistration))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
