// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: helloworld/v1/c2n.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	C2N_SayHello_FullMethodName = "/c2n.v1.C2N/SayHello"
)

// C2NClient is the client API for C2N service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type C2NClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type c2NClient struct {
	cc grpc.ClientConnInterface
}

func NewC2NClient(cc grpc.ClientConnInterface) C2NClient {
	return &c2NClient{cc}
}

func (c *c2NClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, C2N_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// C2NServer is the server API for C2N service.
// All implementations must embed UnimplementedC2NServer
// for forward compatibility.
//
// The greeting service definition.
type C2NServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedC2NServer()
}

// UnimplementedC2NServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedC2NServer struct{}

func (UnimplementedC2NServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedC2NServer) mustEmbedUnimplementedC2NServer() {}
func (UnimplementedC2NServer) testEmbeddedByValue()             {}

// UnsafeC2NServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to C2NServer will
// result in compilation errors.
type UnsafeC2NServer interface {
	mustEmbedUnimplementedC2NServer()
}

func RegisterC2NServer(s grpc.ServiceRegistrar, srv C2NServer) {
	// If the following call pancis, it indicates UnimplementedC2NServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&C2N_ServiceDesc, srv)
}

func _C2N_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2NServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: C2N_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2NServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// C2N_ServiceDesc is the grpc.ServiceDesc for C2N service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var C2N_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "c2n.v1.C2N",
	HandlerType: (*C2NServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _C2N_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/v1/c2n.proto",
}
