// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type SignParticipationRequest struct {
	UserAddress     string `json:"user_address"`
	ContractAddress string `json:"contract_address"`
	Amount          string `json:"amount"`
}

type SignParticipationResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"`
}

type SignRegistrationRequest struct {
	UserAddress     string `json:"user_address"`
	ContractAddress string `json:"contract_address"`
}

type SignRegistrationResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"`
}
